NP-84- Creata recommendation functions

diff --git a/src/Dockerfile.server b/src/Dockerfile.server
--- a/src/Dockerfile.server
+++ b/src/Dockerfile.server
@@ -5,24 +5,19 @@ FROM gcc:latest
 RUN apt-get update && apt-get install -y cmake g++ make
 
 # Copy server files into the container
-COPY . /usr/src/myserver
+COPY . /usr/src
 
 # Set working directory inside the container
-WORKDIR /usr/src/myserver
-
-# Clean up unnecessary files
-RUN rm -rf build CMakeCache.txt CMakeFiles cmake_install.cmake Makefile
+WORKDIR /usr/src
 
 # Create build directory and change into it
 RUN mkdir build
-WORKDIR /usr/src/myserver/build
-
+WORKDIR /usr/src/build
 
 # Run CMake to build the project
 RUN cmake .. && make
 
-# Expose the port the server will listen on
-#EXPOSE 12345
+RUN ls /esr/src/myserver/build/runProject || echo "Executables not found!"
 
 # Command to run the server
 ENTRYPOINT ["./runProject"]
